spring:
  application:
    name: registration-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:https://service-registry.local.pcfdev.io}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    
user-service:
  ribbon:
    listOfServers: user-service-subintroductive-quenchableness.cfapps.io