spring:
  application:
    name: polarizer-registration-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:https://polarizer-service-registry.cfapps.io/}/eureka/
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 1
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  ReadTimeout: 1000

feign:
  hystrix:
    enabled: true
  
hystrix:
  metrics:
    enabled: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
