server:
  host: polarizer-user-service.local.pcfdev.io
spring:
  application:
    name: polarizer-user-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:https://polarizer-service-registry.cfapps.io/}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true