spring:
  application:
    name: polarizer-registration-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:https://polarizer-service-registry.local.pcfdev.io}/eureka/
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 1
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
