spring:
  application:
    name: polarizer-registration-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:https://polarizer-service-registry.local.pcfdev.io}/eureka/
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 1
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true

ribbon:
  ReadTimeout: 5000

feign:
  hystrix:
    enabled: true
  oauth2:
    enabled: true
  
hystrix:
  metrics:
    enabled: true
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 10000

security:
  oauth2:
    resource:
      userInfoUri: https://polarizer-authorization-service.local.pcfdev.io/uaa/user
  ignored: /hystrix, /hystrix.stream, /hystrix/**, /webjars/**, /proxy.stream